services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mtg
      POSTGRES_USER: mtguser
      POSTGRES_PASSWORD: mtgpass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://mtguser:mtgpass@db:5432/mtg

volumes:
  dbdata:
